In [ ]:
1:10
15:5
-1:-10
-10:-5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 15 14 13 12 11 10  9  8  7  6  5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

[1] -10  -9  -8  -7  -6  -5

In [ ]:
1.23:10
-1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1] -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77  6.77  7.77  8.77  9.77

In [ ]:
seq(10)
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
x = 2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [ ]:
x = seq(1, 50, 1/2)
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [ ]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

In [ ]:
x = c(9,8,7,6)
ind = seq(along=x)
ind

[1] 1 2 3 4

In [ ]:
x[ ind[2] ]

[1] 8

In [ ]:
Sys.time()
Sys.Date()

[1] "2026-09-03 04:25:03 UTC"

[1] "2026-09-03"

In [ ]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [ ]:
seq(as.Date("2017-01-01"), by = "days",length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [ ]:
seq(as.Date("2017-01-01"), by = "years",length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

In [ ]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
letters[1:3]
letters[2]

[1] "a" "b" "c"

[1] "b"

In [ ]:
LETTERS
LETTERS[1:3]
LETTERS[2]

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C"

[1] "B"

In [ ]:
rep(3.5, times=10)
rep(1:4,each = 2)
rep(1:4,each = 2, times = 3)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
ans = seq(from=2, to=8, by=2)
ans

[1] 2 4 6 8

In [ ]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [ ]:
rep(2, length.out=5)
rep("apple", length=5)

[1] 2 2 2 2 2

[1] "apple" "apple" "apple" "apple" "apple"

In [ ]:
y = c(8,5,7,6)
y

[1] 8 5 7 6

In [ ]:
sort(y)

[1] 5 6 7 8

In [ ]:
sort(y, decreasing = TRUE)

[1] 8 7 6 5

In [ ]:
y = c(9,8,5,7,6)
y

[1] 9 8 5 7 6

In [ ]:
order(y)
order(y,decreasing = TRUE)

[1] 3 5 4 2 1

[1] 1 2 4 5 3

In [ ]:
mode(2.432)
mode(c(3,4,5,6,7,8))
mode("INDIA")
mode(c("INDIA",123))
mode(factor(c("UP","MP")))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

[1] "numeric"

In [ ]:
mode(list("India", "USA"))
mode(data.frame(x=1:2,y = c("INdia","Canada")))
mode(print)

[1] "list"

[1] "list"

[1] "function"

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1
x2
x1+x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

In [ ]:
x1[2,1] = "hello"
x1
x1+x2

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
matlist = list(x1,x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1 = list( c("water", "juice", "lemonade"),
rep(1:4, each=2), matrix(data=5:8, nrow=2,
ncol=2, byrow=T) )
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [ ]:
z1[[1]]
z1[[2]]
z1[[3]]

[1] "water"    "juice"    "lemonade"

[1] 1 1 2 2 3 3 4 4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [ ]:
z1[[1]][2]
z1[1][2]

[1] "juice"

[[1]]
NULL